apiVersion: v1
kind: Service
metadata:
  labels:
    app: minimal-nodejs-kubernetes-example
  name: minimal-nodejs-kubernetes-example
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9093
  selector:
    app: minimal-nodejs-kubernetes-example
  sessionAffinity: None
  type: LoadBalancer