apiVersion: v1
kind: Service
metadata:
  labels:
    app: koatest
  name: koatest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9093
  selector:
    app: koatest
  sessionAffinity: None
  type: LoadBalancer