apiVersion: v1
kind: ReplicationController
metadata:
  name: minimal-nodejs-kubernetes-example
spec:
  replicas: 2
  selector:
    app: minimal-nodejs-kubernetes-example
  template:
    metadata:
      name: minimal-nodejs-kubernetes-example
      labels:
        app: minimal-nodejs-kubernetes-example
    spec:
      containers:
      - name: minimal-nodejs-kubernetes-example
        image: ulikoehler/minimal-nodejs-kubernetes-example:v1.0
        ports:
        - containerPort: 9093
